# -*- coding: utf-8 -*-
"""OpenCV(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JINS7llXMQshAnl_7zzz_xTvEnpDefs
"""

pip install opencv-python

from google.colab import files
uploaded = files.upload()

# Importing the OpenCV library
import cv2

# Reading the image using imread() function
image = cv2.imread('image.jpg')

# Check if image was loaded successfully
if image is None:
    print("Error: Could not load image. Please ensure 'image.jpg' exists and the path is correct.")
else:
    # Extracting the height and width of an image
    h, w = image.shape[:2]
    # Displaying the height and width
    print("Height = {}, Width = {}".format(h, w))

# Extracting RGB values.
# Here we have randomly chosen a pixel
# by passing in 100, 100 for height and width.
(B, G, R) = image[100, 100]

# Displaying the pixel values
print("R = {}, G = {}, B = {}".format(R, G, B))

# We can also pass the channel to extract
# the value for a specific channel
B = image[100, 100, 0]
print("B = {}".format(B))

# We will calculate the region of interest
# by slicing the pixels of the image
from google.colab.patches import cv2_imshow
roi = image[100 : 500, 200 : 700] # [start_row:end_row,start_col:end_col]
cv2_imshow(roi)

# resize() function takes 2 parameters,
# the image and the dimensions
from google.colab.patches import cv2_imshow
resize = cv2.resize(image, (300, 300))  #[image,(height,width)]
cv2_imshow(resize)

# We are copying the original image,
# as it is an in-place operation.
output = image.copy()

# Using the rectangle() function to create a rectangle.
rectangle = cv2.rectangle(output, (80, 90),
                        (60, 400), (255, 0, 0), 2)
cv2_imshow(rectangle)

# Copying the original image
output = image.copy()

# Adding the text using putText() function
text = cv2.putText(output, 'First OpenCV done!!', (40, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 2, (25, 0, 0), 2)   #[image,text,coordinates,font,font-size,color,line width]

cv2_imshow(text)

